[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"

[fmt]
multiline_func_header = "all"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options